//! LDPC(240, 74) codec with CRC-24 for the WSJT FST4W family.
//!
//! 50 message bits + 24 CRC bits → 240-bit codeword (`lib/fst4/encode240_74.f90`),
//! decoded as `lib/fst4/decode240_74.f90` does at `v3.3.0-beta1`: tanh-product
//! belief propagation that stops early, then the ordered-statistics decoder
//! ([`fastosd`]) run on the BP's accumulated soft output. Tables are in
//! [`tables`], generated by `scripts/fst4w/gen_ldpc_tables.py`.
//!
//! This is its own BP loop rather than [`crate::fec::ldpc::bp`]'s, on purpose:
//!
//! - upstream's `platanh` here is a piecewise-linear approximation of `atanh`
//!   (`lib/platanh.f90`), not the clamped `atanh` the generic BP calls;
//! - `zsave(:,i)` is the running sum of the BP output after iteration `i`, kept
//!   for `maxosd` iterations, and each is handed to OSD in turn;
//! - `Keff = 50` shortens BP to one iteration (`maxiterations = 1`).
//!
//! `zn(i) = llr(i) + Σ tov` is summed in the same order, with the same `f32`
//! tanh, so the oracle test (`tests/fst4w_fec_upstream.rs`) can require an exact
//! match.

pub mod fastosd;
pub mod tables;

#[cfg(not(feature = "std"))]
#[allow(unused_imports)]
// needed with no std in the graph; a dep linking std makes f32's own methods shadow it
use num_traits::Float;

use crate::fec::ldpc::osd::ldpc_encode_generic;
use crate::fec::ldpc::params::{Ldpc240_74Params, LdpcParams};

use crate::engine::{FecCodec, FecOpts, FecResult};
pub use crate::fec::ldpc240_101::crc24;
use alloc::vec::Vec;
pub use fastosd::{FastOsd74, Osd74Work, fastosd240_74};

pub const LDPC_N: usize = 240;
pub const LDPC_K: usize = 74;
pub const LDPC_M: usize = LDPC_N - LDPC_K; // 166
/// Message payload bits; the other 24 of the 74 are the CRC.
pub const PAYLOAD_BITS: usize = 50;
/// Column weight: each bit is in three checks (`ncw = 3`).
const NCW: usize = 3;
const MAX_ROW: usize = <Ldpc240_74Params as LdpcParams>::MAX_ROW;

/// 50 payload bits → the 74 bits the encoder takes: the CRC-24 over the 74-bit
/// word with its CRC slot zeroed, appended MSB first (`genfst4.f90`,
/// `get_crc24(msgbits,74,...)`).
pub fn append_crc24_50(payload: &[u8; PAYLOAD_BITS]) -> [u8; LDPC_K] {
    let mut info = [0u8; LDPC_K];
    info[..PAYLOAD_BITS].copy_from_slice(payload);
    let crc = crc24(&info);
    for i in 0..24 {
        info[PAYLOAD_BITS + i] = ((crc >> (23 - i)) & 1) as u8;
    }
    info
}

/// `get_crc24(m74, 74) == 0`: the 74-bit word carries a consistent CRC.
pub fn check_crc24_74(word: &[u8]) -> bool {
    word.len() == LDPC_K && crc24(word) == 0
}

/// `encode240_74`: systematic encode of 74 bits (payload + CRC).
pub fn encode(info: &[u8; LDPC_K]) -> [u8; LDPC_N] {
    let mut cw = [0u8; LDPC_N];
    ldpc_encode_generic::<Ldpc240_74Params>(info, &mut cw);
    cw
}

/// `lib/platanh.f90`, in `f32`.
fn platanh(x: f32) -> f32 {
    let mut isign = 1.0f32;
    let mut z = x;
    if x < 0.0 {
        isign = -1.0;
        z = x.abs();
    }
    if z <= 0.664 {
        x / 0.83
    } else if z <= 0.9217 {
        (isign * (z - 0.4064)) / 0.322
    } else if z <= 0.9951 {
        (isign * (z - 0.8378)) / 0.0524
    } else if z <= 0.9998 {
        (isign * (z - 0.9914)) / 0.0012
    } else {
        isign * 7.0
    }
}

/// A `decode240_74` success.
#[derive(Clone, Debug)]
pub struct Decoded74 {
    pub message74: [u8; LDPC_K],
    pub cw: [u8; LDPC_N],
    /// 1 = BP; `1 + i` = OSD on `zsave(:, i)`.
    pub ntype: u8,
    /// Hard errors against the *input* LLRs.
    pub nharderror: u32,
    /// Σ|llr| over those errors.
    pub dmin: f32,
}

/// `decode240_74_owned(work, llr, Keff, maxosd, norder, apmask, ...)`.
///
/// `maxosd < 0`: BP only. `maxosd == 0`: OSD once on the channel LLRs.
/// `maxosd > 0` (capped at 3): BP, then OSD on the saved BP outputs.
/// `norder` is the OSD depth (`ndeep`). `apmask`, when given, holds those bits
/// at their channel LLR through BP. `None` is a failed decode (`ntype = 0`).
pub fn decode240_74(
    work: &mut Osd74Work,
    llr: &[f32],
    keff: usize,
    maxosd: i32,
    norder: i32,
    apmask: Option<&[bool]>,
) -> Option<Decoded74> {
    assert_eq!(llr.len(), LDPC_N);
    let maxiterations: i32 = if keff == 50 { 1 } else { 30 };
    let mut maxosd = maxosd;
    let nosd;
    let mut zsave = [[0f32; LDPC_N]; 3];
    if maxosd > 3 {
        maxosd = 3;
    }
    if maxosd == 0 {
        nosd = 1;
        zsave[0].copy_from_slice(llr);
    } else if maxosd > 0 {
        nosd = maxosd as usize;
    } else {
        nosd = 0;
    }

    let hard_errors = |cw: &[u8; LDPC_N]| {
        let mut n = 0u32;
        let mut d = 0f32;
        for i in 0..LDPC_N {
            let hdec = u8::from(llr[i] >= 0.0);
            if hdec ^ cw[i] != 0 {
                n += 1;
                d += llr[i].abs();
            }
        }
        (n, d)
    };

    if maxosd != 0 {
        let mut tov = [[0f32; NCW]; LDPC_N];
        let mut toc = [[0f32; MAX_ROW]; LDPC_M];
        let mut tanhtoc = [[0f32; MAX_ROW]; LDPC_M];
        let mut zn = [0f32; LDPC_N];
        let mut zsum = [0f32; LDPC_N];
        let mut cw = [0u8; LDPC_N];
        let mut ncnt = 0i32;
        let mut nclast = 0i32;

        for iter in 0..=maxiterations {
            // Update bit log likelihood ratios (tov=0 in iteration 0).
            for i in 0..LDPC_N {
                if apmask.is_none_or(|m| !m[i]) {
                    let mut s = 0f32;
                    for t in &tov[i] {
                        s += t;
                    }
                    zn[i] = llr[i] + s;
                } else {
                    zn[i] = llr[i];
                }
            }
            for i in 0..LDPC_N {
                zsum[i] += zn[i];
            }
            if iter > 0 && iter <= maxosd {
                zsave[(iter - 1) as usize] = zsum;
            }

            // Check to see if we have a codeword.
            for i in 0..LDPC_N {
                cw[i] = u8::from(zn[i] > 0.0);
            }
            let mut ncheck = 0i32;
            for i in 0..LDPC_M {
                let mut synd = 0u32;
                for s in 0..Ldpc240_74Params::nrw(i) as usize {
                    synd += cw[Ldpc240_74Params::nm(i, s) as usize] as u32;
                }
                if !synd.is_multiple_of(2) {
                    ncheck += 1;
                }
            }
            if ncheck == 0 {
                let mut m74 = [0u8; LDPC_K];
                m74.copy_from_slice(&cw[..LDPC_K]);
                if crc24(&m74) == 0 {
                    let (n, d) = hard_errors(&cw);
                    return Some(Decoded74 {
                        message74: m74,
                        cw,
                        ntype: 1,
                        nharderror: n,
                        dmin: d,
                    });
                }
            }

            if iter > 0 {
                // early stopping criterion
                let nd = ncheck - nclast;
                if nd < 0 {
                    ncnt = 0;
                } else {
                    ncnt += 1;
                }
                if ncnt >= 5 && iter >= 10 && ncheck > 15 {
                    break;
                }
            }
            nclast = ncheck;

            // Send messages from bits to check nodes.
            for j in 0..LDPC_M {
                for i in 0..Ldpc240_74Params::nrw(j) as usize {
                    let ibj = Ldpc240_74Params::nm(j, i) as usize;
                    toc[j][i] = zn[ibj];
                    for kk in 0..NCW {
                        if Ldpc240_74Params::mn(ibj)[kk] as usize == j {
                            toc[j][i] -= tov[ibj][kk];
                        }
                    }
                }
            }

            // Send messages from check nodes to variable nodes.
            for i in 0..LDPC_M {
                for s in 0..MAX_ROW {
                    tanhtoc[i][s] = (-toc[i][s] / 2.0).tanh();
                }
            }
            for j in 0..LDPC_N {
                for i in 0..NCW {
                    let ichk = Ldpc240_74Params::mn(j)[i] as usize;
                    let mut tmn = 1.0f32;
                    for s in 0..Ldpc240_74Params::nrw(ichk) as usize {
                        if Ldpc240_74Params::nm(ichk, s) as usize != j {
                            tmn *= tanhtoc[ichk][s];
                        }
                    }
                    tov[j][i] = 2.0 * platanh(-tmn);
                }
            }
        }
    }

    for (i, zs) in zsave.iter().enumerate().take(nosd) {
        let r = fastosd240_74(work, zs, keff, norder);
        if r.nhardmin > 0 {
            let (n, d) = hard_errors(&r.cw);
            return Some(Decoded74 {
                message74: r.message74,
                cw: r.cw,
                ntype: 2 + i as u8,
                nharderror: n,
                dmin: d,
            });
        }
    }
    None
}

/// Zero-sized LDPC(240, 74) codec for [`crate::engine::Protocol::Fec`].
///
/// `decode_soft` is `decode240_74(Keff = 66, maxosd = 2, norder = 3)` — the first
/// rung of `fst4_decode.f90:740`'s ladder — with a fresh generator cache per
/// call. FST4W's own decoder (`fst4w::decode`) keeps the cache and runs both
/// rungs; this exists so the trait surface is complete.
#[derive(Copy, Clone, Debug, Default)]
pub struct Ldpc240_74;

impl crate::engine::protocol::sealed::Sealed for Ldpc240_74 {}
impl FecCodec for Ldpc240_74 {
    const N: usize = LDPC_N;
    const K: usize = LDPC_K;

    fn encode(&self, info: &[u8], codeword: &mut [u8]) {
        assert_eq!(info.len(), LDPC_K, "info must be {} bits", LDPC_K);
        assert_eq!(codeword.len(), LDPC_N, "codeword must be {} bits", LDPC_N);
        ldpc_encode_generic::<Ldpc240_74Params>(info, codeword);
    }

    fn decode_soft(&self, llr: &[f32], _opts: &FecOpts<'_>) -> Option<FecResult> {
        let mut work = Osd74Work::new();
        let r = decode240_74(&mut work, llr, 66, 2, 3, None)?;
        Some(FecResult {
            info: Vec::from(r.message74),
            hard_errors: r.nharderror,
            iterations: 0,
        })
    }
}

impl crate::engine::protocol::BpPooledFec for Ldpc240_74 {
    /// No BP scratch: [`decode240_74`] keeps its messages on the stack, and the
    /// generator cache it does reuse belongs to the decoder
    /// ([`Osd74Work`]), not to a call.
    type Scratch = ();

    fn decode_soft_pooled(
        &self,
        llr: &[f32],
        opts: &FecOpts<'_>,
        _scratch: &mut Self::Scratch,
    ) -> Option<FecResult> {
        self.decode_soft(llr, opts)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn word(seed: u32) -> [u8; LDPC_K] {
        let mut p = [0u8; PAYLOAD_BITS];
        for (i, b) in p.iter_mut().enumerate() {
            *b = ((seed.wrapping_mul(2_654_435_761) >> (i % 29)) & 1) as u8;
        }
        append_crc24_50(&p)
    }

    #[test]
    fn crc_roundtrip() {
        for s in 0..16 {
            let w = word(s);
            assert!(check_crc24_74(&w));
            let mut bad = w;
            bad[s as usize % 50] ^= 1;
            assert!(!check_crc24_74(&bad));
        }
    }

    #[test]
    fn perfect_llr_decodes_by_bp() {
        let w = word(5);
        let cw = encode(&w);
        let llr: Vec<f32> = cw
            .iter()
            .map(|&b| if b == 1 { 8.0 } else { -8.0 })
            .collect();
        let mut work = Osd74Work::new();
        let r = decode240_74(&mut work, &llr, 66, 2, 3, None).expect("decodes");
        assert_eq!(r.message74, w);
        assert_eq!(r.ntype, 1);
        assert_eq!(r.nharderror, 0);
    }
}
