//! MSK144 TX synthesis: a 77-bit WSJT message -> CRC-13 ->
//! LDPC(128,90) -> 144 binary tones -> repeated real audio.
//!
//! Ported from WSJT-X `genmsk_128_90.f90`. Message packing
//! (`pack77`/CRC-13) and LDPC encoding are the caller's job — see
//! [`crate::msg::wsjt77`] and [`crate::fec::Ldpc128_90`] — this module
//! covers only the MSK144-specific channel framing, delegating the
//! OQPSK waveform math to [`crate::core::dsp::msk`].

use num_complex::Complex32;

use crate::core::FecCodec;
use crate::core::dsp::msk::{NSPM, build_bitseq, synth_frame};
use crate::fec::Ldpc128_90;
use crate::fec::ldpc_128_90::crc13;

/// Synthesise the 864-sample complex baseband frame for a 128-bit
/// LDPC(128,90) codeword (already produced by
/// [`crate::fec::Ldpc128_90::encode`](crate::core::FecCodec::encode)).
/// Convenience wrapper combining [`build_bitseq`] + [`synth_frame`].
pub fn synth_codeword_frame(codeword: &[u8; 128]) -> [Complex32; NSPM] {
    let bitseq = build_bitseq(codeword);
    synth_frame(&bitseq)
}

/// Add the WSJT-X CRC-13 field to a 77-bit MSK144 payload.
pub fn message77_with_crc(message77: &[u8; 77]) -> [u8; 90] {
    let mut info = [0u8; 90];
    info[..77].copy_from_slice(message77);
    let mut bytes = [0u8; 12];
    for (index, &bit) in message77.iter().enumerate() {
        bytes[index / 8] |= (bit & 1) << (7 - index % 8);
    }
    let checksum = crc13(&bytes);
    for index in 0..13 {
        info[77 + index] = ((checksum >> (12 - index)) & 1) as u8;
    }
    info
}

/// Encode a 77-bit message into the 144 audio-tone values generated by
/// WSJT-X `genmsk_128_90.f90` after its final polarity flip.
pub fn message77_to_tones(message77: &[u8; 77]) -> [u8; 144] {
    let info = message77_with_crc(message77);
    let mut codeword = [0u8; 128];
    Ldpc128_90.encode(&info, &mut codeword);
    let channel = build_bitseq(&codeword);
    let bipolar = channel.map(|bit| 2 * bit as i8 - 1);
    let mut tones = [0u8; 144];
    for index in 0..72 {
        let odd_product = i16::from(bipolar[2 * index + 1]) * i16::from(bipolar[2 * index]);
        let even_product =
            i16::from(bipolar[2 * index + 1]) * i16::from(bipolar[(2 * index + 2) % 144]);
        let before_flip_odd = (odd_product + 1) / 2;
        let before_flip_even = (1 - even_product) / 2;
        tones[2 * index] = (1 - before_flip_odd) as u8;
        tones[2 * index + 1] = (1 - before_flip_even) as u8;
    }
    tones
}

fn pack_text(text: &str) -> Option<[u8; 77]> {
    crate::msg::wsjt77::pack77_message(text)
}

/// Synthesize a complete one-shot MSK144 period at 12 kHz.
///
/// The 72 ms message frame repeats continuously, exactly like WSJT-X's
/// fast-mode modulator. Audio ends 0.5 s before the slot boundary; the
/// caller applies its configured hardware-output ramp around this buffer.
pub fn tones_to_period_audio(
    tones: &[u8; 144],
    period_seconds: u32,
    center_frequency_hz: f32,
    amplitude: f32,
) -> Option<alloc::vec::Vec<f32>> {
    if !matches!(period_seconds, 5 | 10 | 15 | 30)
        || !center_frequency_hz.is_finite()
        || !(600.0..=5_400.0).contains(&center_frequency_hz)
        || !amplitude.is_finite()
        || !(0.0..=1.0).contains(&amplitude)
    {
        return None;
    }
    let sample_count = (period_seconds as usize * 12_000).saturating_sub(6_000);
    let mut audio = alloc::vec::Vec::with_capacity(sample_count);
    let mut phase = 0.0f32;
    let base_frequency = center_frequency_hz - 500.0;
    for sample_index in 0..sample_count {
        let tone = tones[(sample_index / 6) % tones.len()];
        let frequency = base_frequency + tone as f32 * 1_000.0;
        phase += core::f32::consts::TAU * frequency / 12_000.0;
        if phase >= core::f32::consts::TAU {
            phase -= core::f32::consts::TAU;
        }
        audio.push(amplitude * phase.sin());
    }
    Some(audio)
}

/// Pack and synthesize a standard or free-text MSK144 transmission.
pub fn synthesize_text_period(
    text: &str,
    period_seconds: u32,
    center_frequency_hz: f32,
    amplitude: f32,
) -> Option<alloc::vec::Vec<f32>> {
    let message = pack_text(text)?;
    let tones = message77_to_tones(&message);
    tones_to_period_audio(&tones, period_seconds, center_frequency_hz, amplitude)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::dsp::msk::{build_bitseq, matched_filter_softbits};
    use crate::core::{FecCodec, FecOpts};
    use crate::fec::Ldpc128_90;
    use crate::fec::ldpc_128_90::check_crc13;
    use crate::msg::wsjt77::pack77;

    fn build_info_with_crc(pattern: impl Fn(usize) -> u8) -> [u8; 90] {
        let mut info = [0u8; 90];
        for i in 0..77 {
            info[i] = pattern(i);
        }
        let mut bytes = [0u8; 12];
        for (i, &b) in info[..77].iter().enumerate() {
            let byte_idx = i / 8;
            let bit_pos = 7 - (i % 8);
            bytes[byte_idx] |= (b & 1) << bit_pos;
        }
        let crc = crate::fec::ldpc_128_90::crc13(&bytes);
        for i in 0..13 {
            info[77 + i] = ((crc >> (12 - i)) & 1) as u8;
        }
        info
    }

    /// WSJT-X normalization (`msk144decodeframe.f90:85-93`): zero-mean
    /// / unit-variance softbits, then `llr = 2*softbit/sigma^2` with
    /// the fixed `sigma=0.60` magic constant, over just the 128
    /// data-bit softbits (both embedded sync words are skipped: bits
    /// 8..56 and 64..144, 0-based).
    fn softbits_to_data_llr(softbits: &[f32; 144]) -> [f32; 128] {
        let mean: f32 = softbits.iter().sum::<f32>() / 144.0;
        let var: f32 = softbits
            .iter()
            .map(|s| (s - mean) * (s - mean))
            .sum::<f32>()
            / 144.0;
        let sigma_sig = var.sqrt();

        const SIGMA: f32 = 0.60;
        let mut llr = [0.0f32; 128];
        for (i, v) in llr[0..48].iter_mut().enumerate() {
            *v = 2.0 * (softbits[8 + i] / sigma_sig) / (SIGMA * SIGMA);
        }
        for (i, v) in llr[48..128].iter_mut().enumerate() {
            *v = 2.0 * (softbits[64 + i] / sigma_sig) / (SIGMA * SIGMA);
        }
        llr
    }

    /// End-to-end: encode -> build channel frame -> matched filter ->
    /// scale to LLR -> LDPC decode, at zero CFO / perfect timing /
    /// zero carrier phase. Exercises the full DSP chain added in
    /// Phase 2 plus Phase 1's codec.
    #[test]
    fn clean_frame_roundtrips_through_ldpc() {
        let info = build_info_with_crc(|i| ((i * 7 + 3) & 1) as u8);
        assert!(check_crc13(&info));

        let mut codeword = [0u8; 128];
        Ldpc128_90.encode(&info, &mut codeword);

        let frame = synth_codeword_frame(&codeword);
        let softbits = matched_filter_softbits(&frame);

        // Hard-decision check: every softbit's sign must match its
        // transmitted bipolar bit.
        let bitseq = build_bitseq(&codeword);
        for i in 0..144 {
            assert_eq!(
                softbits[i] > 0.0,
                bitseq[i] == 1,
                "softbit {i} sign mismatch"
            );
        }

        let llr = softbits_to_data_llr(&softbits);
        let opts = FecOpts {
            verify_info: Some(check_crc13),
            ..Default::default()
        };
        let r = Ldpc128_90
            .decode_soft(&llr, &opts)
            .expect("BP converges on clean synth frame");
        assert_eq!(&r.info[..77], &info[..77]);
    }

    /// Same chain, but with an arbitrary constant carrier-phase offset
    /// applied before demodulation, to genuinely exercise the
    /// carrier-phase estimate/derotation step (a phase-0 test alone
    /// wouldn't meaningfully exercise it since derotation would be a
    /// near-no-op).
    #[test]
    fn phase_rotated_frame_still_decodes() {
        let info = build_info_with_crc(|i| ((i * 3 + 5) & 1) as u8);
        let mut codeword = [0u8; 128];
        Ldpc128_90.encode(&info, &mut codeword);

        let mut frame = synth_codeword_frame(&codeword);
        let phase = 0.7_f32; // arbitrary, non-trivial constant phase offset
        let rot = Complex32::new(phase.cos(), phase.sin());
        for c in frame.iter_mut() {
            *c *= rot;
        }

        let softbits = matched_filter_softbits(&frame);
        let bitseq = build_bitseq(&codeword);
        for i in 0..144 {
            assert_eq!(
                softbits[i] > 0.0,
                bitseq[i] == 1,
                "softbit {i} sign mismatch under phase rotation"
            );
        }

        let llr = softbits_to_data_llr(&softbits);
        let opts = FecOpts {
            verify_info: Some(check_crc13),
            ..Default::default()
        };
        let r = Ldpc128_90
            .decode_soft(&llr, &opts)
            .expect("BP converges under constant phase rotation");
        assert_eq!(&r.info[..77], &info[..77]);
    }

    /// Deterministic small perturbation (not true AWGN -- this crate's
    /// convention for fast unit tests is a reproducible per-index
    /// pattern rather than an RNG dependency, see
    /// `fec::ldpc_128_90::tests::roundtrip_noisy_llr_recovers`) added
    /// to a handful of samples, confirming the full chain tolerates
    /// small distortion rather than requiring bit-exact synth input.
    #[test]
    fn mildly_perturbed_frame_still_decodes() {
        let info = build_info_with_crc(|i| ((i * 5 + 1) & 1) as u8);
        let mut codeword = [0u8; 128];
        Ldpc128_90.encode(&info, &mut codeword);

        let mut frame = synth_codeword_frame(&codeword);
        for (k, c) in frame.iter_mut().enumerate() {
            // Small deterministic perturbation, amplitude well below
            // the unit-pulse peak, applied to every 7th sample.
            if k % 7 == 0 {
                let n = (k as f32 * 12.9898).sin() * 43_758.547;
                let pseudo = n - n.floor() - 0.5; // in [-0.5, 0.5)
                *c += Complex32::new(0.15 * pseudo, -0.15 * pseudo);
            }
        }

        let softbits = matched_filter_softbits(&frame);
        let llr = softbits_to_data_llr(&softbits);
        let opts = FecOpts {
            verify_info: Some(check_crc13),
            ..Default::default()
        };
        let r = Ldpc128_90
            .decode_soft(&llr, &opts)
            .expect("BP converges under mild perturbation");
        assert_eq!(&r.info[..77], &info[..77]);
    }

    #[test]
    fn production_tones_match_the_pinned_fortran_mapping() {
        let message = pack77("CQ", "K1ABC", "FN42").expect("pack");
        let info = message77_with_crc(&message);
        assert!(check_crc13(&info));
        let tones = message77_to_tones(&message);
        assert!(tones.iter().all(|tone| *tone <= 1));

        let mut codeword = [0u8; 128];
        Ldpc128_90.encode(&info, &mut codeword);
        let channel = build_bitseq(&codeword).map(|bit| 2 * bit as i8 - 1);
        for index in 0..72 {
            let first = i16::from(channel[2 * index + 1]) * i16::from(channel[2 * index]);
            let second =
                i16::from(channel[2 * index + 1]) * i16::from(channel[(2 * index + 2) % 144]);
            assert_eq!(tones[2 * index], (1 - (first + 1) / 2) as u8);
            assert_eq!(tones[2 * index + 1], (1 - (1 - second) / 2) as u8);
        }
    }

    #[test]
    fn every_selectable_period_has_the_wsjt_x_stop_margin() {
        let message = pack77("CQ", "K1ABC", "FN42").expect("pack");
        let tones = message77_to_tones(&message);
        for period in [5, 10, 15, 30] {
            let audio = tones_to_period_audio(&tones, period, 1_500.0, 0.3).expect("valid period");
            assert_eq!(audio.len(), period as usize * 12_000 - 6_000,);
            assert!(audio.iter().all(|sample| sample.abs() <= 0.300_001));
        }
    }

    #[cfg(any(feature = "fft-rustfft", feature = "fft-extern"))]
    #[test]
    fn production_period_audio_round_trips_through_slot_decoder() {
        use crate::msk144::decode::{Depth, decode_slot};

        let audio = synthesize_text_period("CQ K1ABC FN42", 5, 1_500.0, 0.8)
            .expect("valid production message");
        let pcm: alloc::vec::Vec<i16> = audio
            .iter()
            .map(|sample| (sample * 30_000.0) as i16)
            .collect();
        let decodes = decode_slot(&pcm, 1_500.0, 8.0, Depth::Deep);
        assert!(
            decodes
                .iter()
                .any(|decode| decode.message == "CQ K1ABC FN42"),
            "production audio did not round-trip: {decodes:?}",
        );
    }
}
