// SPDX-License-Identifier: GPL-3.0-or-later
//! Corpus resolution for golden (tier-B) tests, and the mechanism that
//! stops a missing corpus from passing as a green test.
//!
//! ## The problem this exists to fix
//!
//! Every WSJT-X-sample test in this suite used to resolve its audio
//! from `../../WSJT-X/samples/…` — a *sibling checkout*, present only
//! on a developer machine — and skip with `eprintln!("skipping…");
//! return;` when it wasn't there. CI has no such checkout, so on CI
//! all of `fst4_wsjtx_samples`, `q65_wsjtx_samples`,
//! `wspr_wsjtx_samples`, `ft4_wsjtx_samples` and
//! `msk144_wsjtx_samples` **skipped and reported success**, while
//! `ci.yml` described one of those very tiers as "load-bearing
//! regression protection". Measured 2026-08-11: CI's `default` suite
//! executed ~17 s of tests, essentially all compile time, and the only
//! protocols genuinely covered were FT8 and JT9 — the two whose
//! recordings happen to be committed to the repo.
//!
//! ## The fix, in two halves
//!
//! 1. **Vendor the recordings** into `embedded-poc/assets/golden/` so
//!    CI has them at all (~8.7 MB; the WSJT-X samples are GPL, same as
//!    this crate). [`golden_dir`] resolves there first.
//! 2. **Make absence loud where it matters.** [`require_corpus`]
//!    returns `None` (skip, as before) on a developer machine, but
//!    **panics** when `MFSK_REQUIRE_CORPUS=1` — which CI sets. A
//!    corpus that goes missing in CI is then a failure, not a silent
//!    pass.
//!
//! Tier-C sweep corpora (`embedded-poc/assets/*_sweep/`, ~17 GB,
//! gitignored, regenerated by `scripts/gen_*_sweep_wavs.sh`) are
//! deliberately *not* covered by `MFSK_REQUIRE_CORPUS` — they are not
//! meant to run in CI at all. Use [`optional_corpus`] for those so the
//! distinction stays visible at the call site.

use std::path::{Path, PathBuf};

/// Env var CI sets to turn a missing tier-B corpus into a hard failure.
pub const REQUIRE_ENV: &str = "MFSK_REQUIRE_CORPUS";

fn require_enabled() -> bool {
    std::env::var(REQUIRE_ENV).is_ok_and(|v| v != "0" && !v.is_empty())
}

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Root of the vendored golden recordings
/// (`embedded-poc/assets/golden/`).
#[allow(dead_code)]
pub fn golden_dir() -> PathBuf {
    manifest_dir().join("../embedded-poc/assets/golden")
}

/// Resolve a **tier-B golden** asset, e.g.
/// `golden_path("wspr/150426_0918.wav")`.
///
/// Resolution order:
/// 1. `embedded-poc/assets/golden/<rel>` (vendored — what CI uses)
/// 2. `$WSJTX_SAMPLES_DIR/<rel_upstream>` when the caller supplies an
///    upstream-relative fallback via [`golden_path_or_upstream`]
///
/// Returns `None` if absent — **unless** `MFSK_REQUIRE_CORPUS` is set,
/// in which case it panics. Callers should treat `None` as "skip this
/// test" and say so with `eprintln!`.
#[allow(dead_code)]
pub fn golden_path(rel: &str) -> Option<PathBuf> {
    golden_path_or_upstream(rel, None)
}

/// [`golden_path`] with an optional `$WSJTX_SAMPLES_DIR`-relative
/// fallback, for assets that are not vendored (large Q65 sub-mode
/// trees, say) but that a developer machine may still have.
#[allow(dead_code)]
pub fn golden_path_or_upstream(rel: &str, upstream_rel: Option<&str>) -> Option<PathBuf> {
    let vendored = golden_dir().join(rel);
    if vendored.exists() {
        return Some(vendored);
    }
    if let Some(up) = upstream_rel
        && let Ok(dir) = std::env::var("WSJTX_SAMPLES_DIR")
    {
        let p = Path::new(&dir).join(up);
        if p.exists() {
            return Some(p);
        }
    }
    if require_enabled() {
        panic!(
            "{REQUIRE_ENV} is set but the golden asset {rel:?} is missing \
             (looked in {}). A tier-B golden test cannot be allowed to skip \
             in CI — that is exactly the failure mode this mechanism exists \
             to prevent. Either vendor the asset under \
             embedded-poc/assets/golden/ or drop the test.",
            golden_dir().display()
        );
    }
    None
}

/// Same contract as [`golden_path`] for a whole directory.
#[allow(dead_code)]
pub fn golden_subdir(rel: &str) -> Option<PathBuf> {
    let p = golden_dir().join(rel);
    if p.is_dir() {
        return Some(p);
    }
    if require_enabled() {
        panic!(
            "{REQUIRE_ENV} is set but the golden directory {rel:?} is missing \
             (looked in {})",
            golden_dir().display()
        );
    }
    None
}

/// Resolve a **tier-C** (sensitivity sweep) corpus directory.
///
/// Deliberately *never* panics under `MFSK_REQUIRE_CORPUS`: these
/// corpora are ~17 GB, gitignored, regenerated by
/// `scripts/gen_*_sweep_wavs.sh`, and are not meant to run in CI. A
/// separate function rather than a flag so the tier is obvious at the
/// call site.
#[allow(dead_code)]
pub fn optional_corpus(rel: &str) -> Option<PathBuf> {
    let p = manifest_dir().join("../embedded-poc/assets").join(rel);
    p.is_dir().then_some(p)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vendored_golden_assets_are_present() {
        // These are committed to the repo, so their absence is a real
        // failure on any machine, not a skip.
        for rel in [
            "ft4/000000_000002.wav",
            "fst4/210115_0058.wav",
            "wspr/150426_0918.wav",
            "msk144/181211_120500.wav",
            "msk144/181211_120800.wav",
            "jt65/jt65a_5sig_m18.wav",
        ] {
            assert!(
                golden_dir().join(rel).exists(),
                "vendored golden asset {rel} is missing from {}",
                golden_dir().display()
            );
        }
    }

    #[test]
    fn missing_asset_is_none_without_the_env_var() {
        // Guard the developer-machine half of the contract. (The
        // panicking half is exercised by CI itself running the whole
        // tier-B suite with MFSK_REQUIRE_CORPUS=1.)
        if require_enabled() {
            return;
        }
        assert!(golden_path("nope/does-not-exist.wav").is_none());
    }
}
