#ifndef MFSK_FFI_H
#define MFSK_FFI_H

#pragma once

/* Generated by cbindgen — do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Protocol tag selecting which decoder / synth family this handle
 * (or encode call) drives.
 */
typedef enum MfskProtocol {
    /**
     * FT8 — 15 s slot, 8-GFSK, LDPC(174,91), 77-bit WSJT message.
     */
    MFSK_PROTOCOL_FT8 = 0,
    /**
     * FT4 — 7.5 s slot, 4-GFSK, LDPC(174,91), 77-bit WSJT message.
     */
    MFSK_PROTOCOL_FT4 = 1,
    /**
     * WSPR — 120 s slot, 4-FSK, convolutional r=½ K=32 + Fano, 50-bit payload.
     */
    MFSK_PROTOCOL_WSPR = 2,
    /**
     * JT9 — 60 s slot, 9-FSK, convolutional r=½ K=32 + Fano, 72-bit JT message.
     */
    MFSK_PROTOCOL_JT9 = 3,
    /**
     * JT65 — 60 s slot, 65-FSK, Reed-Solomon(63,12) over GF(2⁶), 72-bit JT message.
     */
    MFSK_PROTOCOL_JT65 = 4,
    /**
     * FST4-60A — 60 s slot, 4-GFSK, LDPC(240,101) + CRC-24, 77-bit WSJT message.
     */
    MFSK_PROTOCOL_FST4S60 = 5,
} MfskProtocol;

/**
 * Status / error code returned by every fallible `mfsk_*` call.
 *
 * Zero is success. Negative values indicate errors; use
 * [`mfsk_last_error`] for a human-readable description.
 */
typedef enum MfskStatus {
    /**
     * Success.
     */
    MFSK_STATUS_OK = 0,
    /**
     * A caller-supplied argument was invalid (null pointer to a
     * non-optional arg, out-of-range size, malformed string, etc.).
     */
    MFSK_STATUS_INVALID_ARG = -1,
    /**
     * The supplied protocol tag is not recognised or not supported
     * by this build (e.g. FST4 in a build that was compiled without
     * the `fst4` feature would report this at decode / encode time).
     */
    MFSK_STATUS_UNKNOWN_PROTOCOL = -2,
    /**
     * The decoder ran without a fatal error but produced no results;
     * the message list is empty. Used by some encode helpers to
     * signal that the message could not be packed into the protocol
     * payload (e.g. unsupported callsign format).
     */
    MFSK_STATUS_DECODE_FAILED = -3,
    /**
     * Internal error: an invariant of the Rust implementation was
     * violated (e.g. a `Box::from_raw` got a bad pointer). Always a bug.
     */
    MFSK_STATUS_INTERNAL = -4,
} MfskStatus;

/**
 * Opaque decoder handle. Construct with [`mfsk_decoder_new`], release
 * with [`mfsk_decoder_free`].
 */
typedef struct MfskDecoder {
    uint8_t _priv[0];
} MfskDecoder;

/**
 * One successfully decoded message.
 */
typedef struct MfskMessage {
    /**
     * Carrier (tone-0) frequency in Hz.
     */
    float freq_hz;
    /**
     * Time offset in seconds from the protocol's nominal frame start.
     */
    float dt_sec;
    /**
     * WSJT-X compatible SNR in dB (2500 Hz reference bandwidth).
     */
    float snr_db;
    /**
     * Hard-decision errors corrected by the FEC.
     */
    uint32_t hard_errors;
    /**
     * Decode pass identifier (matches the Rust `DecodeResult::pass`).
     */
    uint8_t pass;
    /**
     * UTF-8, NUL-terminated message text. Owned by the parent
     * [`MfskMessageList`]; do not free individually.
     */
    char *text;
} MfskMessage;

/**
 * List of decoded messages returned from a decode call. Caller should
 * zero-initialise before the call; callee fills `items` / `len`.
 */
typedef struct MfskMessageList {
    /**
     * Array of `len` `MfskMessage` values.
     */
    struct MfskMessage *items;
    /**
     * Number of entries in `items`.
     */
    uintptr_t len;
    /**
     * Internal: total allocation (reserved for future growth).
     */
    uintptr_t _cap;
} MfskMessageList;

/**
 * A buffer of synthesised f32 PCM samples returned by `mfsk_encode_*`.
 * Caller should zero-initialise before the call and free with
 * [`mfsk_samples_free`] when done reading.
 */
typedef struct MfskSamples {
    /**
     * Contiguous f32 PCM at the protocol's native sample rate
     * (12 000 Hz for all currently-supported modes). Owned by the
     * list; free with [`mfsk_samples_free`].
     */
    float *samples;
    /**
     * Number of f32 entries in `samples`.
     */
    uintptr_t len;
    /**
     * Internal: total allocation (reserved for future growth).
     */
    uintptr_t _cap;
} MfskSamples;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns a pointer to the thread-local last-error string, or NULL if
 * no error has been recorded on this thread. The pointer is valid until
 * the next fallible call on this thread.
 */
const char *mfsk_last_error(void);

/**
 * Construct a new decoder handle bound to `protocol`. Returns NULL on
 * failure (see [`mfsk_last_error`]).
 */
struct MfskDecoder *mfsk_decoder_new(enum MfskProtocol protocol);

/**
 * Destroy a decoder handle previously returned by [`mfsk_decoder_new`].
 * Passing NULL is a no-op.
 *
 * # Safety
 *
 * `dec` must be a pointer previously returned by [`mfsk_decoder_new`],
 * or NULL. After this call the pointer is dangling.
 */
void mfsk_decoder_free(struct MfskDecoder *dec);

/**
 * Free a [`MfskMessageList`] populated by a decode call. Passing NULL
 * or an already-freed list is safe.
 *
 * # Safety
 *
 * `list` must point to a [`MfskMessageList`] written by one of the
 * `mfsk_decode_*` functions, or be NULL. After this call, `items` is
 * NULL and `len` is 0.
 */
void mfsk_message_list_free(struct MfskMessageList *list);

/**
 * Free a [`MfskSamples`] buffer populated by a `mfsk_encode_*` call.
 * Passing NULL or an already-freed buffer is safe.
 *
 * # Safety
 *
 * `s` must point to a [`MfskSamples`] written by one of the
 * `mfsk_encode_*` functions, or be NULL. After this call, `samples`
 * is NULL and `len` is 0.
 */
void mfsk_samples_free(struct MfskSamples *s);

/**
 * Decode one slot of f32 PCM audio.
 *
 * The protocol to decode is whichever was passed to
 * [`mfsk_decoder_new`]; the sample duration is implicit in the
 * protocol's slot length (FT8 = 15 s, FT4 = 7.5 s, FST4-60A / JT9 /
 * JT65 = 60 s, WSPR = 120 s). The audio must already be aligned to
 * the slot boundary — this function does not search for sync outside
 * the slot. Non-12 kHz input is linearly resampled to 12 000 Hz
 * internally.
 *
 * On success, `out` is filled with the list of decoded messages
 * (may be empty). The caller owns the list and must release it with
 * [`mfsk_message_list_free`].
 *
 * Samples should be scaled to roughly ±1.0 (full-scale sine = 1.0).
 *
 * # Parameters
 *
 * - `dec` — decoder handle from [`mfsk_decoder_new`].
 * - `samples` — pointer to `n_samples` `f32` PCM values, slot-aligned.
 * - `n_samples` — number of samples in `samples`.
 * - `sample_rate` — sample rate of `samples` in Hz (commonly 12000,
 *   48000, or 44100). Must be ≥ 8000 Hz.
 * - `out` — pointer to a caller-allocated `MfskMessageList` that is
 *   either zero-initialised or previously freed via
 *   [`mfsk_message_list_free`].
 *
 * # Returns
 *
 * [`MfskStatus::Ok`] on success (including zero decodes). On failure
 * returns an error status and `out` is left unchanged; consult
 * [`mfsk_last_error`] for details.
 *
 * # Safety
 *
 * - `dec` must be a live [`MfskDecoder`] handle.
 * - `samples` must point to `n_samples` valid `f32` values.
 * - `out` must point to a writable [`MfskMessageList`]; caller must
 *   pair with [`mfsk_message_list_free`].
 */
enum MfskStatus mfsk_decode_f32(const struct MfskDecoder *dec,
                                const float *samples,
                                uintptr_t n_samples,
                                uint32_t sample_rate,
                                struct MfskMessageList *out);

/**
 * Decode one slot of 16-bit signed PCM audio.
 *
 * Identical to [`mfsk_decode_f32`] but takes interleaved `i16`
 * samples (the direct output of most ADCs and WAV files). Full-scale
 * input is `±32767`. See [`mfsk_decode_f32`] for parameter semantics,
 * return values, and slot-alignment requirements.
 *
 * # Safety
 *
 * See [`mfsk_decode_f32`].
 */
enum MfskStatus mfsk_decode_i16(const struct MfskDecoder *dec,
                                const int16_t *samples,
                                uintptr_t n_samples,
                                uint32_t sample_rate,
                                struct MfskMessageList *out);

/**
 * Synthesise a standard FT8 message ("CALL1 CALL2 REPORT") at `freq_hz`
 * carrier. Writes 12 kHz f32 PCM into `out`.
 *
 * # Safety
 *
 * `call1`/`call2`/`report` must be NUL-terminated UTF-8 strings.
 * `out` must be a writable `MfskSamples` (zero-initialise).
 */
enum MfskStatus mfsk_encode_ft8(const char *call1,
                                const char *call2,
                                const char *report,
                                float freq_hz,
                                struct MfskSamples *out);

/**
 * Synthesise a standard FT4 message at `freq_hz`. 12 kHz f32 PCM.
 *
 * # Safety
 *
 * See [`mfsk_encode_ft8`].
 */
enum MfskStatus mfsk_encode_ft4(const char *call1,
                                const char *call2,
                                const char *report,
                                float freq_hz,
                                struct MfskSamples *out);

/**
 * Synthesise a standard FST4-60A message at `freq_hz`. 12 kHz f32 PCM.
 *
 * # Safety
 *
 * See [`mfsk_encode_ft8`].
 */
enum MfskStatus mfsk_encode_fst4s60(const char *call1,
                                    const char *call2,
                                    const char *report,
                                    float freq_hz,
                                    struct MfskSamples *out);

/**
 * Synthesise a Type-1 WSPR message (`call grid power_dbm`).
 *
 * # Safety
 *
 * See [`mfsk_encode_ft8`].
 */
enum MfskStatus mfsk_encode_wspr(const char *call,
                                 const char *grid,
                                 int32_t power_dbm,
                                 float freq_hz,
                                 struct MfskSamples *out);

/**
 * Synthesise a standard JT9 message at `freq_hz`.
 *
 * # Safety
 *
 * See [`mfsk_encode_ft8`].
 */
enum MfskStatus mfsk_encode_jt9(const char *call1,
                                const char *call2,
                                const char *grid_or_report,
                                float freq_hz,
                                struct MfskSamples *out);

/**
 * Synthesise a standard JT65 message at `freq_hz`.
 *
 * # Safety
 *
 * See [`mfsk_encode_ft8`].
 */
enum MfskStatus mfsk_encode_jt65(const char *call1,
                                 const char *call2,
                                 const char *grid_or_report,
                                 float freq_hz,
                                 struct MfskSamples *out);

/**
 * Library version, major.minor.patch packed into a 32-bit integer (8
 * bits per field). Useful for the consumer to sanity-check ABI
 * compatibility.
 */
uint32_t mfsk_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MFSK_FFI_H */
