#ifndef MFSK_FFI_H
#define MFSK_FFI_H

#pragma once

/* Generated by cbindgen — do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Protocol tag selecting which decoder / synth family this handle
 * (or encode call) drives.
 */
typedef enum MfskProtocol {
    /**
     * FT8 — 15 s slot, 8-GFSK, LDPC(174,91), 77-bit WSJT message.
     */
    MFSK_PROTOCOL_FT8 = 0,
    /**
     * FT4 — 7.5 s slot, 4-GFSK, LDPC(174,91), 77-bit WSJT message.
     */
    MFSK_PROTOCOL_FT4 = 1,
    /**
     * WSPR — 120 s slot, 4-FSK, convolutional r=½ K=32 + Fano, 50-bit payload.
     */
    MFSK_PROTOCOL_WSPR = 2,
    /**
     * JT9 — 60 s slot, 9-FSK, convolutional r=½ K=32 + Fano, 72-bit JT message.
     */
    MFSK_PROTOCOL_JT9 = 3,
    /**
     * JT65 — 60 s slot, 65-FSK, Reed-Solomon(63,12) over GF(2⁶), 72-bit JT message.
     */
    MFSK_PROTOCOL_JT65 = 4,
    /**
     * FST4-60A — 60 s slot, 4-GFSK, LDPC(240,101) + CRC-24, 77-bit WSJT message.
     */
    MFSK_PROTOCOL_FST4S60 = 5,
    /**
     * Q65-30A — 30 s slot, 65-FSK, QRA(15,65) over GF(64), 77-bit WSJT message.
     * Other Q65 sub-modes (60A..60E for EME) are reachable via
     * the dedicated `mfsk_q65_*` function family with a
     * [`MfskQ65SubMode`] parameter.
     */
    MFSK_PROTOCOL_Q65A30 = 6,
} MfskProtocol;

/**
 * Status / error code returned by every fallible `mfsk_*` call.
 *
 * Zero is success. Negative values indicate errors; use
 * [`mfsk_last_error`] for a human-readable description.
 */
typedef enum MfskStatus {
    /**
     * Success.
     */
    MFSK_STATUS_OK = 0,
    /**
     * A caller-supplied argument was invalid (null pointer to a
     * non-optional arg, out-of-range size, malformed string, etc.).
     */
    MFSK_STATUS_INVALID_ARG = -1,
    /**
     * The supplied protocol tag is not recognised or not supported
     * by this build (e.g. FST4 in a build that was compiled without
     * the `fst4` feature would report this at decode / encode time).
     */
    MFSK_STATUS_UNKNOWN_PROTOCOL = -2,
    /**
     * The decoder ran without a fatal error but produced no results;
     * the message list is empty. Used by some encode helpers to
     * signal that the message could not be packed into the protocol
     * payload (e.g. unsupported callsign format).
     */
    MFSK_STATUS_DECODE_FAILED = -3,
    /**
     * Internal error: an invariant of the Rust implementation was
     * violated (e.g. a `Box::from_raw` got a bad pointer). Always a bug.
     */
    MFSK_STATUS_INTERNAL = -4,
} MfskStatus;

/**
 * Q65 sub-mode selector for the dedicated `mfsk_q65_*` function
 * family. All sub-modes share the same FEC, sync layout and
 * message format — only the T/R period and tone spacing change.
 *
 * Picked from the type-level `Q65a30 / Q65a60 / Q65b60 / Q65c60 /
 * Q65d60 / Q65e60` ZSTs in `mfsk_core::q65`.
 */
typedef enum MfskQ65SubMode {
    /**
     * Q65-30A — 30 s slot, ×1 spacing. Terrestrial weak-signal
     * HF/VHF and ionoscatter; the most common Q65 sub-mode.
     */
    MFSK_Q65_SUB_MODE_A30 = 0,
    /**
     * Q65-60A — 60 s slot, ×1 spacing. 6 m EME.
     */
    MFSK_Q65_SUB_MODE_A60 = 1,
    /**
     * Q65-60B — 60 s slot, ×2 spacing. 70 cm / 23 cm EME.
     */
    MFSK_Q65_SUB_MODE_B60 = 2,
    /**
     * Q65-60C — 60 s slot, ×4 spacing. ~3 GHz microwave EME.
     */
    MFSK_Q65_SUB_MODE_C60 = 3,
    /**
     * Q65-60D — 60 s slot, ×8 spacing. 5.7 / 10 GHz EME (libration
     * spread requires the fast-fading metric).
     */
    MFSK_Q65_SUB_MODE_D60 = 4,
    /**
     * Q65-60E — 60 s slot, ×16 spacing. 24 GHz+ / extreme spread.
     */
    MFSK_Q65_SUB_MODE_E60 = 5,
} MfskQ65SubMode;

/**
 * Channel-spread fading model used by `mfsk_q65_decode_fading`.
 * Matches the Gaussian / Lorentzian calibration tables shipped
 * with WSJT-X.
 */
typedef enum MfskQ65FadingModel {
    /**
     * Gaussian-spread channel — fits libration-limited EME and
     * most AWGN-with-jitter scenarios.
     */
    MFSK_Q65_FADING_MODEL_GAUSSIAN = 0,
    /**
     * Lorentzian-spread channel — heavier tails; fits some
     * ionoscatter / meteor-burst signatures.
     */
    MFSK_Q65_FADING_MODEL_LORENTZIAN = 1,
} MfskQ65FadingModel;

/**
 * Opaque decoder handle. Construct with [`mfsk_decoder_new`], release
 * with [`mfsk_decoder_free`].
 */
typedef struct MfskDecoder {
    uint8_t _priv[0];
} MfskDecoder;

/**
 * One successfully decoded message.
 */
typedef struct MfskMessage {
    /**
     * Carrier (tone-0) frequency in Hz.
     */
    float freq_hz;
    /**
     * Time offset in seconds from the protocol's nominal frame start.
     */
    float dt_sec;
    /**
     * WSJT-X compatible SNR in dB (2500 Hz reference bandwidth).
     */
    float snr_db;
    /**
     * Hard-decision errors corrected by the FEC.
     */
    uint32_t hard_errors;
    /**
     * Decode pass identifier (matches the Rust `DecodeResult::pass`).
     */
    uint8_t pass;
    /**
     * UTF-8, NUL-terminated message text. Owned by the parent
     * [`MfskMessageList`]; do not free individually.
     */
    char *text;
} MfskMessage;

/**
 * List of decoded messages returned from a decode call. Caller should
 * zero-initialise before the call; callee fills `items` / `len`.
 */
typedef struct MfskMessageList {
    /**
     * Array of `len` `MfskMessage` values.
     */
    struct MfskMessage *items;
    /**
     * Number of entries in `items`.
     */
    uintptr_t len;
    /**
     * Internal: total allocation (reserved for future growth).
     */
    uintptr_t _cap;
} MfskMessageList;

/**
 * A buffer of synthesised f32 PCM samples returned by `mfsk_encode_*`.
 * Caller should zero-initialise before the call and free with
 * [`mfsk_samples_free`] when done reading.
 */
typedef struct MfskSamples {
    /**
     * Contiguous f32 PCM at the protocol's native sample rate
     * (12 000 Hz for all currently-supported modes). Owned by the
     * list; free with [`mfsk_samples_free`].
     */
    float *samples;
    /**
     * Number of f32 entries in `samples`.
     */
    uintptr_t len;
    /**
     * Internal: total allocation (reserved for future growth).
     */
    uintptr_t _cap;
} MfskSamples;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns a pointer to the thread-local last-error string, or NULL if
 * no error has been recorded on this thread. The pointer is valid until
 * the next fallible call on this thread.
 */
const char *mfsk_last_error(void);

/**
 * Construct a new decoder handle bound to `protocol`. Returns NULL on
 * failure (see [`mfsk_last_error`]).
 */
struct MfskDecoder *mfsk_decoder_new(enum MfskProtocol protocol);

/**
 * Destroy a decoder handle previously returned by [`mfsk_decoder_new`].
 * Passing NULL is a no-op.
 *
 * # Safety
 *
 * `dec` must be a pointer previously returned by [`mfsk_decoder_new`],
 * or NULL. After this call the pointer is dangling.
 */
void mfsk_decoder_free(struct MfskDecoder *dec);

/**
 * Free a [`MfskMessageList`] populated by a decode call. Passing NULL
 * or an already-freed list is safe.
 *
 * # Safety
 *
 * `list` must point to a [`MfskMessageList`] written by one of the
 * `mfsk_decode_*` functions, or be NULL. After this call, `items` is
 * NULL and `len` is 0.
 */
void mfsk_message_list_free(struct MfskMessageList *list);

/**
 * Free a [`MfskSamples`] buffer populated by a `mfsk_encode_*` call.
 * Passing NULL or an already-freed buffer is safe.
 *
 * # Safety
 *
 * `s` must point to a [`MfskSamples`] written by one of the
 * `mfsk_encode_*` functions, or be NULL. After this call, `samples`
 * is NULL and `len` is 0.
 */
void mfsk_samples_free(struct MfskSamples *s);

/**
 * Decode one slot of f32 PCM audio.
 *
 * The protocol to decode is whichever was passed to
 * [`mfsk_decoder_new`]; the sample duration is implicit in the
 * protocol's slot length (FT8 = 15 s, FT4 = 7.5 s, FST4-60A / JT9 /
 * JT65 = 60 s, WSPR = 120 s). The audio must already be aligned to
 * the slot boundary — this function does not search for sync outside
 * the slot. Non-12 kHz input is linearly resampled to 12 000 Hz
 * internally.
 *
 * On success, `out` is filled with the list of decoded messages
 * (may be empty). The caller owns the list and must release it with
 * [`mfsk_message_list_free`].
 *
 * Samples should be scaled to roughly ±1.0 (full-scale sine = 1.0).
 *
 * # Parameters
 *
 * - `dec` — decoder handle from [`mfsk_decoder_new`].
 * - `samples` — pointer to `n_samples` `f32` PCM values, slot-aligned.
 * - `n_samples` — number of samples in `samples`.
 * - `sample_rate` — sample rate of `samples` in Hz (commonly 12000,
 *   48000, or 44100). Must be ≥ 8000 Hz.
 * - `out` — pointer to a caller-allocated `MfskMessageList` that is
 *   either zero-initialised or previously freed via
 *   [`mfsk_message_list_free`].
 *
 * # Returns
 *
 * [`MfskStatus::Ok`] on success (including zero decodes). On failure
 * returns an error status and `out` is left unchanged; consult
 * [`mfsk_last_error`] for details.
 *
 * # Safety
 *
 * - `dec` must be a live [`MfskDecoder`] handle.
 * - `samples` must point to `n_samples` valid `f32` values.
 * - `out` must point to a writable [`MfskMessageList`]; caller must
 *   pair with [`mfsk_message_list_free`].
 */
enum MfskStatus mfsk_decode_f32(const struct MfskDecoder *dec,
                                const float *samples,
                                uintptr_t n_samples,
                                uint32_t sample_rate,
                                struct MfskMessageList *out);

/**
 * Decode one slot of 16-bit signed PCM audio.
 *
 * Identical to [`mfsk_decode_f32`] but takes interleaved `i16`
 * samples (the direct output of most ADCs and WAV files). Full-scale
 * input is `±32767`. See [`mfsk_decode_f32`] for parameter semantics,
 * return values, and slot-alignment requirements.
 *
 * # Safety
 *
 * See [`mfsk_decode_f32`].
 */
enum MfskStatus mfsk_decode_i16(const struct MfskDecoder *dec,
                                const int16_t *samples,
                                uintptr_t n_samples,
                                uint32_t sample_rate,
                                struct MfskMessageList *out);

/**
 * Synthesise a standard FT8 message ("CALL1 CALL2 REPORT") at `freq_hz`
 * carrier. Writes 12 kHz f32 PCM into `out`.
 *
 * # Safety
 *
 * `call1`/`call2`/`report` must be NUL-terminated UTF-8 strings.
 * `out` must be a writable `MfskSamples` (zero-initialise).
 */
enum MfskStatus mfsk_encode_ft8(const char *call1,
                                const char *call2,
                                const char *report,
                                float freq_hz,
                                struct MfskSamples *out);

/**
 * Synthesise a standard FT4 message at `freq_hz`. 12 kHz f32 PCM.
 *
 * # Safety
 *
 * See [`mfsk_encode_ft8`].
 */
enum MfskStatus mfsk_encode_ft4(const char *call1,
                                const char *call2,
                                const char *report,
                                float freq_hz,
                                struct MfskSamples *out);

/**
 * Synthesise a standard FST4-60A message at `freq_hz`. 12 kHz f32 PCM.
 *
 * # Safety
 *
 * See [`mfsk_encode_ft8`].
 */
enum MfskStatus mfsk_encode_fst4s60(const char *call1,
                                    const char *call2,
                                    const char *report,
                                    float freq_hz,
                                    struct MfskSamples *out);

/**
 * Synthesise a Type-1 WSPR message (`call grid power_dbm`).
 *
 * # Safety
 *
 * See [`mfsk_encode_ft8`].
 */
enum MfskStatus mfsk_encode_wspr(const char *call,
                                 const char *grid,
                                 int32_t power_dbm,
                                 float freq_hz,
                                 struct MfskSamples *out);

/**
 * Synthesise a standard JT9 message at `freq_hz`.
 *
 * # Safety
 *
 * See [`mfsk_encode_ft8`].
 */
enum MfskStatus mfsk_encode_jt9(const char *call1,
                                const char *call2,
                                const char *grid_or_report,
                                float freq_hz,
                                struct MfskSamples *out);

/**
 * Synthesise a standard JT65 message at `freq_hz`.
 *
 * # Safety
 *
 * See [`mfsk_encode_ft8`].
 */
enum MfskStatus mfsk_encode_jt65(const char *call1,
                                 const char *call2,
                                 const char *grid_or_report,
                                 float freq_hz,
                                 struct MfskSamples *out);

/**
 * Synthesise a standard Q65 message at `freq_hz` for the requested
 * sub-mode. 12 kHz f32 PCM. The 30 s vs 60 s slot duration and tone
 * spacing follow the Q65 spec; the FEC and message format are
 * shared across every sub-mode.
 *
 * # Safety
 *
 * See [`mfsk_encode_ft8`].
 */
enum MfskStatus mfsk_encode_q65(enum MfskQ65SubMode submode,
                                const char *call1,
                                const char *call2,
                                const char *grid_or_report,
                                float freq_hz,
                                struct MfskSamples *out);

/**
 * Plain AWGN Q65 scan-and-decode for any sub-mode. The default
 * strategy — every other `mfsk_q65_decode_*` function trades
 * computational cost or extra inputs for a few dB of threshold gain
 * against this baseline.
 *
 * # Safety
 *
 * `samples` must point to `n_samples` valid `f32` values.
 * `out` must point to a writable [`MfskMessageList`]; pair with
 * [`mfsk_message_list_free`] when done.
 */
enum MfskStatus mfsk_q65_decode(enum MfskQ65SubMode submode,
                                const float *samples,
                                uintptr_t n_samples,
                                uint32_t sample_rate,
                                struct MfskMessageList *out);

/**
 * AP-biased Q65 scan-and-decode. Up to four optional hints
 * (`call1`, `call2`, `grid`, `report`) — each may be NULL when
 * unknown. Lifts the effective decode threshold by ~2 dB when the
 * supplied hints are correct.
 *
 * # Safety
 *
 * As [`mfsk_q65_decode`]. The four hint strings, when non-NULL,
 * must be NUL-terminated UTF-8.
 */
enum MfskStatus mfsk_q65_decode_with_ap(enum MfskQ65SubMode submode,
                                        const float *samples,
                                        uintptr_t n_samples,
                                        uint32_t sample_rate,
                                        const char *ap_call1,
                                        const char *ap_call2,
                                        const char *ap_grid,
                                        const char *ap_report,
                                        struct MfskMessageList *out);

/**
 * Fast-fading Q65 scan-and-decode. Recovers the 5–8 dB the AWGN
 * Bessel front end loses on Doppler-spread channels — required for
 * microwave EME at 5.7 GHz / 10 GHz / 24 GHz. `b90_ts` is the
 * spread bandwidth × symbol period (typical: 0.05 = near-AWGN,
 * 1.0 = moderate, 5.0+ = severe). `model` chooses the calibration
 * shape.
 *
 * # Safety
 *
 * As [`mfsk_q65_decode`].
 */
enum MfskStatus mfsk_q65_decode_fading(enum MfskQ65SubMode submode,
                                       const float *samples,
                                       uintptr_t n_samples,
                                       uint32_t sample_rate,
                                       float b90_ts,
                                       enum MfskQ65FadingModel fading_model,
                                       struct MfskMessageList *out);

/**
 * AP-list (template-matching) Q65 scan-and-decode. Builds the
 * standard 206-codeword candidate set internally from
 * `(my_call, his_call, his_grid)` and picks the matching exchange,
 * if any. `his_grid` may be NULL or empty to skip the two
 * grid-bearing templates. Yields ~3 dB threshold gain over plain
 * BP when the truth is in the candidate set.
 *
 * # Safety
 *
 * As [`mfsk_q65_decode`]. `my_call` and `his_call` must be
 * NUL-terminated UTF-8 strings; `his_grid` may be NULL or
 * NUL-terminated UTF-8.
 */
enum MfskStatus mfsk_q65_decode_with_ap_list(enum MfskQ65SubMode submode,
                                             const float *samples,
                                             uintptr_t n_samples,
                                             uint32_t sample_rate,
                                             const char *my_call,
                                             const char *his_call,
                                             const char *his_grid,
                                             struct MfskMessageList *out);

/**
 * Library version, major.minor.patch packed into a 32-bit integer (8
 * bits per field). Useful for the consumer to sanity-check ABI
 * compatibility.
 */
uint32_t mfsk_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MFSK_FFI_H */
