#ifndef MFSK_FFI_H
#define MFSK_FFI_H

#pragma once

/* Generated by cbindgen — do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Protocol tag selecting which decoder / synth family this handle
 * (or encode call) drives.
 */
typedef enum MfskProtocol {
    MFSK_PROTOCOL_FT8 = 0,
    MFSK_PROTOCOL_FT4 = 1,
    MFSK_PROTOCOL_WSPR = 2,
    MFSK_PROTOCOL_JT9 = 3,
    MFSK_PROTOCOL_JT65 = 4,
    MFSK_PROTOCOL_FST4S60 = 5,
} MfskProtocol;

/**
 * Status / error code returned by every fallible `mfsk_*` call.
 *
 * Zero is success. Negative values indicate errors; use
 * [`mfsk_last_error`] for a human-readable description.
 */
typedef enum MfskStatus {
    MFSK_STATUS_OK = 0,
    MFSK_STATUS_INVALID_ARG = -1,
    MFSK_STATUS_UNKNOWN_PROTOCOL = -2,
    MFSK_STATUS_DECODE_FAILED = -3,
    MFSK_STATUS_INTERNAL = -4,
} MfskStatus;

/**
 * Opaque decoder handle. Construct with [`mfsk_decoder_new`], release
 * with [`mfsk_decoder_free`].
 */
typedef struct MfskDecoder {
    uint8_t _priv[0];
} MfskDecoder;

/**
 * One successfully decoded message.
 */
typedef struct MfskMessage {
    /**
     * Carrier (tone-0) frequency in Hz.
     */
    float freq_hz;
    /**
     * Time offset in seconds from the protocol's nominal frame start.
     */
    float dt_sec;
    /**
     * WSJT-X compatible SNR in dB (2500 Hz reference bandwidth).
     */
    float snr_db;
    /**
     * Hard-decision errors corrected by the FEC.
     */
    uint32_t hard_errors;
    /**
     * Decode pass identifier (matches the Rust `DecodeResult::pass`).
     */
    uint8_t pass;
    /**
     * UTF-8, NUL-terminated message text. Owned by the parent
     * [`MfskMessageList`]; do not free individually.
     */
    char *text;
} MfskMessage;

/**
 * List of decoded messages returned from a decode call. Caller should
 * zero-initialise before the call; callee fills `items` / `len`.
 */
typedef struct MfskMessageList {
    /**
     * Array of `len` `MfskMessage` values.
     */
    struct MfskMessage *items;
    /**
     * Number of entries in `items`.
     */
    uintptr_t len;
    /**
     * Internal: total allocation (reserved for future growth).
     */
    uintptr_t _cap;
} MfskMessageList;

/**
 * A buffer of synthesised f32 PCM samples returned by `mfsk_encode_*`.
 * Caller should zero-initialise before the call and free with
 * [`mfsk_samples_free`] when done reading.
 */
typedef struct MfskSamples {
    float *samples;
    uintptr_t len;
    uintptr_t _cap;
} MfskSamples;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns a pointer to the thread-local last-error string, or NULL if
 * no error has been recorded on this thread. The pointer is valid until
 * the next fallible call on this thread.
 */
const char *mfsk_last_error(void);

/**
 * Construct a new decoder handle bound to `protocol`. Returns NULL on
 * failure (see [`mfsk_last_error`]).
 */
struct MfskDecoder *mfsk_decoder_new(enum MfskProtocol protocol);

/**
 * Destroy a decoder handle previously returned by [`mfsk_decoder_new`].
 * Passing NULL is a no-op.
 *
 * # Safety
 *
 * `dec` must be a pointer previously returned by [`mfsk_decoder_new`],
 * or NULL. After this call the pointer is dangling.
 */
void mfsk_decoder_free(struct MfskDecoder *dec);

/**
 * Free a [`MfskMessageList`] populated by a decode call. Passing NULL
 * or an already-freed list is safe.
 *
 * # Safety
 *
 * `list` must point to a [`MfskMessageList`] written by one of the
 * `mfsk_decode_*` functions, or be NULL. After this call, `items` is
 * NULL and `len` is 0.
 */
void mfsk_message_list_free(struct MfskMessageList *list);

/**
 * Free a [`MfskSamples`] buffer populated by a `mfsk_encode_*` call.
 * Passing NULL or an already-freed buffer is safe.
 *
 * # Safety
 *
 * `s` must point to a [`MfskSamples`] written by one of the
 * `mfsk_encode_*` functions, or be NULL. After this call, `samples`
 * is NULL and `len` is 0.
 */
void mfsk_samples_free(struct MfskSamples *s);

/**
 * Decode one slot of f32 PCM audio at `sample_rate` Hz (non-12 kHz
 * input is resampled internally). Writes zero-or-more messages into
 * `out`. Dispatches to the right backend by protocol tag.
 *
 * # Safety
 *
 * - `dec` must be a live [`MfskDecoder`] handle.
 * - `samples` must point to `n_samples` valid `f32` values.
 * - `out` must point to a writable [`MfskMessageList`]; caller must
 *   pair with [`mfsk_message_list_free`].
 */
enum MfskStatus mfsk_decode_f32(const struct MfskDecoder *dec,
                                const float *samples,
                                uintptr_t n_samples,
                                uint32_t sample_rate,
                                struct MfskMessageList *out);

/**
 * Decode one slot of 16-bit PCM audio at `sample_rate` Hz.
 *
 * # Safety
 *
 * See [`mfsk_decode_f32`].
 */
enum MfskStatus mfsk_decode_i16(const struct MfskDecoder *dec,
                                const int16_t *samples,
                                uintptr_t n_samples,
                                uint32_t sample_rate,
                                struct MfskMessageList *out);

/**
 * Synthesise a standard FT8 message ("CALL1 CALL2 REPORT") at `freq_hz`
 * carrier. Writes 12 kHz f32 PCM into `out`.
 *
 * # Safety
 *
 * `call1`/`call2`/`report` must be NUL-terminated UTF-8 strings.
 * `out` must be a writable `MfskSamples` (zero-initialise).
 */
enum MfskStatus mfsk_encode_ft8(const char *call1,
                                const char *call2,
                                const char *report,
                                float freq_hz,
                                struct MfskSamples *out);

/**
 * Synthesise a standard FT4 message at `freq_hz`. 12 kHz f32 PCM.
 */
enum MfskStatus mfsk_encode_ft4(const char *call1,
                                const char *call2,
                                const char *report,
                                float freq_hz,
                                struct MfskSamples *out);

/**
 * Synthesise a standard FST4-60A message at `freq_hz`. 12 kHz f32 PCM.
 *
 * # Safety
 *
 * See [`mfsk_encode_ft8`].
 */
enum MfskStatus mfsk_encode_fst4s60(const char *call1,
                                    const char *call2,
                                    const char *report,
                                    float freq_hz,
                                    struct MfskSamples *out);

/**
 * Synthesise a Type-1 WSPR message (`call grid power_dbm`).
 */
enum MfskStatus mfsk_encode_wspr(const char *call,
                                 const char *grid,
                                 int32_t power_dbm,
                                 float freq_hz,
                                 struct MfskSamples *out);

/**
 * Synthesise a standard JT9 message at `freq_hz`.
 */
enum MfskStatus mfsk_encode_jt9(const char *call1,
                                const char *call2,
                                const char *grid_or_report,
                                float freq_hz,
                                struct MfskSamples *out);

/**
 * Synthesise a standard JT65 message at `freq_hz`.
 */
enum MfskStatus mfsk_encode_jt65(const char *call1,
                                 const char *call2,
                                 const char *grid_or_report,
                                 float freq_hz,
                                 struct MfskSamples *out);

/**
 * Library version, major.minor.patch packed into a 32-bit integer (8
 * bits per field). Useful for the consumer to sanity-check ABI
 * compatibility.
 */
uint32_t mfsk_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MFSK_FFI_H */
