# Provenance stamps for the tier-C corpora. Sourced, not run.
#
# WHY THIS EXISTS
#
# A tier-C crossing is only comparable with `docs/notes/sweep-baseline.json`
# when it was measured on the same corpus -- the corpus the generators
# write at MFSK_SIM_SEED=1 since 2026-09-23 (scripts/sim_sgran_stub.c).
# Nothing checked that. On 2026-09-30 a release sweep flagged JT65 +0.68 dB
# worse: the decoder was unchanged, and the local jt65/jt9/wspr corpora
# were July/August ones drawn from /dev/urandom before the stub existed.
# The same session found `target/ft8sim/ft8sim` and `target/ft4sim/ft4sim`,
# the generators' default simulator paths, still unseeded builds from
# July/August -- so running a generator with its defaults would have
# written a fresh unreproducible corpus without a word.
#
# WHAT IT DOES
#
# Generators call `corpus_preflight` before writing and `corpus_stamp`
# after, which leaves `<out-dir>/.corpus-stamp` (key=value) recording the
# seed, the simulator and its sha256, and the commit that generated it.
# `scripts/run-sensitivity-sweeps.sh` calls `corpus_check` and refuses a
# corpus without a stamp or with the wrong seed.
#
# `rng` is one of
#   seeded         the simulator links sim_sgran_stub.c; the seed is
#                  MFSK_SIM_SEED (default 1), and a binary without the stub
#                  is refused -- the stub's getenv literal is what marks it
#   deterministic  the simulator never seeds from the system (fst4sim,
#                  q65sim, sjtty); there is no seed to record

CORPUS_STAMP_FILE=.corpus-stamp

corpus__seed() { echo "${MFSK_SIM_SEED:-1}"; }

corpus__get() { # $1 = stamp file, $2 = key
  sed -n "s/^$2=//p" "$1" | head -1
}

corpus__sha() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1
  else shasum -a 256 "$1" | cut -d' ' -f1; fi
}

# corpus_preflight <out-dir> <simulator> <seeded|deterministic>
# Exits the generator on a simulator or an out-dir that would give a corpus
# of unknown provenance.
corpus_preflight() {
  local dir=$1 sim=$2 rng=$3 stamp
  stamp="$dir/$CORPUS_STAMP_FILE"
  if [[ "$rng" = seeded ]] && ! grep -qa MFSK_SIM_SEED "$sim"; then
    echo "error: $sim was not linked with scripts/sim_sgran_stub.c;" >&2
    echo "  it seeds its noise from /dev/urandom, so the corpus it writes" >&2
    echo "  reproduces nowhere. Rebuild it with this repo's build_*sim.sh." >&2
    exit 1
  fi
  compgen -G "$dir/*.wav" >/dev/null 2>&1 || return 0
  # WAVs are already there and a generator only fills in missing cells, so
  # they must be the same corpus the new cells would join.
  if [[ ! -f "$stamp" ]]; then
    echo "error: $dir holds WAVs with no $CORPUS_STAMP_FILE -- their seed and" >&2
    echo "  simulator are unknown, and new cells would be mixed in with them." >&2
    echo "  Move the directory aside and generate into an empty one." >&2
    exit 1
  fi
  local want_seed="-" have_seed have_sha
  [[ "$rng" = seeded ]] && want_seed="$(corpus__seed)"
  have_seed="$(corpus__get "$stamp" seed)"
  have_sha="$(corpus__get "$stamp" simulator_sha256)"
  if [[ "$have_seed" != "$want_seed" ]]; then
    echo "error: $dir was generated at seed=$have_seed, this run is seed=$want_seed." >&2
    echo "  Generate into a separate out-dir." >&2
    exit 1
  fi
  # Not an error: a rebuild from the same tree need not be byte-identical
  # (gen_jtty_sweep_wavs.sh rebuilds sjtty on every run). The tree is what
  # matters -- ft8sim from 2b9d654 and from 3.x draw different ccir channels
  # (gen_ft8_sweep_wavs.sh) -- and a hash cannot tell a rebuild from that.
  if [[ "$have_sha" != "$(corpus__sha "$sim")" ]]; then
    echo "warning: $dir was generated by a different $(basename "$sim") binary" >&2
    echo "  ($(corpus__get "$stamp" simulator)). If it came from another WSJT-X" >&2
    echo "  tree, stop and generate into a separate out-dir." >&2
  fi
}

# corpus_stamp <out-dir> <simulator> <seeded|deterministic> <generator-script>
corpus_stamp() {
  local dir=$1 sim=$2 rng=$3 gen=$4 root seed="-" dirty=0
  root="$(cd "$(dirname "$gen")/.." && pwd)"
  [[ "$rng" = seeded ]] && seed="$(corpus__seed)"
  git -C "$root" diff --quiet HEAD -- scripts 2>/dev/null || dirty=1
  cat > "$dir/$CORPUS_STAMP_FILE" <<EOF
# Written by $(basename "$gen"); read by scripts/run-sensitivity-sweeps.sh.
# See scripts/lib/corpus-stamp.sh. Do not hand-edit.
generator=$(basename "$gen")
rng=$rng
seed=$seed
simulator=$sim
simulator_sha256=$(corpus__sha "$sim")
commit=$(git -C "$root" rev-parse HEAD 2>/dev/null || echo unknown)
scripts_dirty=$dirty
date=$(date -u +%Y-%m-%dT%H:%M:%SZ)
host=$(uname -n)
EOF
}

# corpus_check <dir> <seeded|deterministic> <repo-root>
# Prints one line of problems (empty when fine) and returns 1 on a
# corpus that must not be compared with the baseline, 0 otherwise.
# Warnings (generator changed since the stamp) print with a "warn:" prefix
# and return 0.
corpus_check() {
  local dir=$1 rng=$2 root=$3 stamp gen commit want_seed="-" have_seed
  stamp="$dir/$CORPUS_STAMP_FILE"
  if [[ ! -f "$stamp" ]]; then
    echo "no $CORPUS_STAMP_FILE: seed and simulator unknown"
    return 1
  fi
  [[ "$rng" = seeded ]] && want_seed="$(corpus__seed)"
  have_seed="$(corpus__get "$stamp" seed)"
  if [[ "$have_seed" != "$want_seed" ]]; then
    echo "stamped seed=$have_seed, expected seed=$want_seed"
    return 1
  fi
  gen="$(corpus__get "$stamp" generator)"
  commit="$(corpus__get "$stamp" commit)"
  # gen_ft8_sweep_wavs.sh / gen_ft8_busy_wavs.py -> build_ft8sim.sh
  local proto="${gen#gen_}"; proto="${proto%%_*}"
  if ! git -C "$root" cat-file -e "$commit^{commit}" 2>/dev/null; then
    echo "warn: generated at $commit, which this clone does not have"
  elif ! git -C "$root" diff --quiet "$commit" HEAD -- "scripts/$gen" \
        "scripts/build_${proto}sim.sh" scripts/sim_sgran_stub.c 2>/dev/null; then
    echo "warn: scripts/$gen or its simulator build changed since ${commit:0:8}"
  fi
  return 0
}
