/* Auto-generated by cbindgen. Do not edit. See mfsk-ffi-ft8/src/lib.rs. */

#ifndef MFSK_FT8_H
#define MFSK_FT8_H

#pragma once

#include <stdint.h>
#include <stddef.h>

/**
 * Decode cost/recall tradeoff, shared across every protocol both FFI
 * crates expose — mirrors `mfsk_core`'s generic
 * `engine::pipeline::DecodeDepth` (`BP_ONLY` / `FULL`).
 *
 * Discriminant `0` is intentionally unassigned — FT8's pre-0.7.0
 * single-metric `Bp` rung was retired (issue #74); existing callers
 * passing `1`/`2` remain valid.
 */
typedef enum MfskDecodeDepth {
  /**
   * Full LLR-variant staircase + BP, no OSD fallback.
   */
  MFSK_DECODE_DEPTH_BP_ALL = 1,
  /**
   * Above + OSD fallback (host-only; a no-op on protocols/builds
   * without an OSD path).
   */
  MFSK_DECODE_DEPTH_BP_ALL_OSD = 2,
} MfskDecodeDepth;

/**
 * Outcome of a fallible `mfsk_*` / `mfsk_ft8_*` call.
 *
 * Zero is success; negative values are errors. Both crates additionally
 * expose a `_last_error()` function (`mfsk_last_error` /
 * `mfsk_ft8_last_error`) returning a human-readable string for the
 * specific failure reason — the numeric code stays a small, stable
 * set; the string carries the detail (e.g. which buffer was too
 * short, which enum value was out of range).
 */
typedef enum MfskStatus {
  /**
   * Success (zero or more results in the output list).
   */
  MFSK_STATUS_OK = 0,
  /**
   * A required pointer argument was null.
   */
  MFSK_STATUS_NULL_POINTER = -1,
  /**
   * A non-null argument was invalid: malformed UTF-8, an
   * out-of-range enum discriminant, an audio buffer too short for
   * the protocol's slot length, a caller-provided output buffer
   * too small, etc. See `_last_error()` for which.
   */
  MFSK_STATUS_INVALID_ARG = -2,
  /**
   * The supplied protocol tag is not recognised or not supported
   * by this build (e.g. a protocol compiled out via feature flags).
   */
  MFSK_STATUS_UNKNOWN_PROTOCOL = -3,
  /**
   * The call ran without a fatal error but produced no usable
   * result — e.g. an encode helper that could not pack the given
   * callsign/grid/report into the protocol's message payload.
   */
  MFSK_STATUS_DECODE_FAILED = -4,
  /**
   * Internal error: an invariant of the Rust implementation was
   * violated. Always a bug; please report it.
   */
  MFSK_STATUS_INTERNAL = -5,
} MfskStatus;

/**
 * Opaque handle returned by [`mfsk_ft8_stream_new`].
 *
 * Owns one resampler + one 12 kHz ring buffer. Single-threaded —
 * callers that capture and decode on different tasks should put the
 * stream on the capture side and copy out via `_peek_latest` for the
 * decoder.
 */
typedef struct MfskFt8Stream MfskFt8Stream;

/**
 * Opaque decode-tuning-options handle (issue #205) — construct with
 * each crate's own `_options_new(...)`, release with
 * `_options_free`.
 *
 * Both `mfsk-ffi` and `mfsk-ffi-ft8` used to hardcode (or take
 * entirely positionally, with no room to add more later) every
 * decode-tuning knob. Wrapping them behind an opaque handle now means
 * a future knob is a new, optional setter function — the options
 * constructor and every decode function's signature stay stable
 * forever; only additive growth on the setter side.
 *
 * Zero-sized marker type + phantom pointer, matching the established
 * `MfskDecoder` opaque-handle shape in `mfsk-ffi` — each consuming
 * crate `Box`es its own private options struct and casts the raw
 * pointer to/from this type. Defined once here purely so both
 * crates' generated headers agree on the type name / pointer shape.
 */
typedef struct MfskDecodeOptions {
  uint8_t _priv[0];
} MfskDecodeOptions;

/**
 * One successfully decoded message, shared shape across every
 * protocol both FFI crates expose.
 *
 * `text` is a fixed inline buffer (not a heap pointer): the whole
 * [`MfskResultList`] is one allocation, freed in one call, with no
 * per-message ownership to track — the model `mfsk-ffi-ft8` already
 * used, now shared by `mfsk-ffi` too (issue #205; previously
 * `mfsk-ffi`'s `MfskMessage` held a heap `CString` pointer per
 * message instead).
 */
typedef struct MfskResult {
  /**
   * NUL-terminated UTF-8 decoded message text. ASCII in practice.
   *
   * Length is [`MFSK_TEXT_BUF_LEN`] (`40`); written as a bare
   * literal here rather than the constant — see
   * [`MFSK_TEXT_BUF_LEN`]'s doc comment for why.
   */
  char text[40];
  /**
   * Carrier (tone-0) frequency in Hz.
   */
  float freq_hz;
  /**
   * Time offset in seconds from the protocol's nominal frame start.
   */
  float dt_sec;
  /**
   * WSJT-X-compatible SNR estimate, dB (2500 Hz reference bandwidth).
   */
  float snr_db;
  /**
   * Hard-decision errors corrected by the FEC (0 if not applicable).
   */
  uint32_t hard_errors;
  /**
   * Decode pass/stage identifier; meaning is protocol-specific.
   */
  uint8_t pass;
  /**
   * Padding to keep the struct's layout stable across compilers.
   */
  uint8_t _pad[3];
} MfskResult;

/**
 * List of decoded messages, owned by the FFI side. Free with the
 * crate's `_result_list_free` function.
 */
typedef struct MfskResultList {
  /**
   * Pointer to the first result, or null if `len == 0`.
   */
  struct MfskResult *items;
  /**
   * Number of valid entries.
   */
  uintptr_t len;
  /**
   * Total allocation length (private — only the free function
   * needs this; may exceed `len`).
   */
  uintptr_t _capacity;
} MfskResultList;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns a pointer to the last-error string recorded by this crate,
 * or an empty string if none has been recorded yet. The pointer is
 * valid until the next fallible call. Mirrors `mfsk-ffi`'s
 * `mfsk_last_error` in shape (NUL-terminated UTF-8, same
 * pointer-lifetime contract) under this crate's own `mfsk_ft8_`
 * prefix.
 *
 * Not thread-safe — see [`MfskDecodeOptions`]'s module doc / this
 * crate's existing single-threaded contract.
 */
 const char *mfsk_ft8_last_error(void);

/**
 * Construct a decode-options handle. `freq_min_hz`/`freq_max_hz`
 * bound the carrier search range (typical: 200, 3000). `sync_min` is
 * the stage-2 candidate threshold (typical 1.0). `max_cand` caps the
 * survivors after Pass 2 (typical 30 for embedded busy-band).
 * `depth` picks the decoder staircase (`MFSK_DECODE_DEPTH_BP_ALL_OSD`
 * is the most thorough).
 *
 * Free with [`mfsk_ft8_options_free`]. A later knob (issue #205)
 * arrives as a new, optional setter function — this constructor's
 * signature and every decode function's signature stay stable.
 */

struct MfskDecodeOptions *mfsk_ft8_options_new(float freq_min_hz,
                                               float freq_max_hz,
                                               float sync_min,
                                               int max_cand,
                                               enum MfskDecodeDepth depth);

/**
 * Free a handle from [`mfsk_ft8_options_new`]. NULL is a no-op.
 *
 * # Safety
 * `opts` must be a pointer previously returned by
 * [`mfsk_ft8_options_new`], or NULL.
 */
 void mfsk_ft8_options_free(struct MfskDecodeOptions *opts);

/**
 * **Primary FT8 decode.** Runs the embedded fixed-point path under
 * `embedded-fixed-point`, or the host-native f32 path under `host`
 * (mutually exclusive builds — see the crate doc comment). `options`
 * may be NULL to use this crate's defaults (200-3000 Hz, sync_min
 * 1.0, max_cand 30, `MFSK_DECODE_DEPTH_BP_ALL_OSD`); build one with
 * [`mfsk_ft8_options_new`] to override.
 *
 * **Breaking change (0.8.0, issue #205)**: this symbol used to be
 * named `mfsk_ft8_decode_i16_alloc` under the `host` feature
 * (`mfsk_ft8_decode_i16` was embedded-only) and took the five tuning
 * knobs positionally instead of via `options`. C callers built
 * against pre-0.8.0 host headers must rename their call site and
 * switch to an `MfskDecodeOptions` handle.
 *
 * # Safety
 * `audio` must point to `n_samples` valid `i16` values; at least
 * 168 000 (14 s × 12 kHz). `options`, if non-NULL, must be a live
 * handle from [`mfsk_ft8_options_new`]. `out` must point to a
 * writable [`MfskResultList`]. Single-threaded — one decode at a
 * time per process.
 */

enum MfskStatus mfsk_ft8_decode_i16(const int16_t *audio,
                                    uintptr_t n_samples,
                                    const struct MfskDecodeOptions *options,
                                    struct MfskResultList *out);

/**
 * See the embedded-feature [`mfsk_ft8_decode_i16`] doc comment — same
 * symbol name, host-native f32 backend (`decode_block`) instead of
 * the embedded fixed-point path.
 *
 * # Safety
 * See the embedded-feature [`mfsk_ft8_decode_i16`].
 */

enum MfskStatus mfsk_ft8_decode_i16(const int16_t *audio,
                                    uintptr_t n_samples,
                                    const struct MfskDecodeOptions *options,
                                    struct MfskResultList *out);

/**
 * Free a result list previously populated by [`mfsk_ft8_decode_i16`].
 * Safe to call with a zero-length list. After this returns, the
 * list's `items` pointer is invalid; the struct itself remains valid
 * for reuse.
 *
 * # Safety
 * `list` must be either null (no-op) or point to a `MfskResultList`
 * previously populated by this crate.
 */
 void mfsk_ft8_result_list_free(struct MfskResultList *list);

/**
 * Required output length (in samples) for the synth functions.
 * Equals `NN × 1920 = 151 680` (12.64 s of 12 kHz mono).
 */
 uintptr_t mfsk_ft8_synth_output_len(void);

/**
 * Pack a standard 77-bit FT8 message from three tokens — the
 * typical CQ shape `mfsk_ft8_pack77("CQ", "JA1ABC", "PM86")`. For
 * reply / report messages: `mfsk_ft8_pack77("JA1ABC", "W1AW",
 * "-12")`. Strings must be NUL-terminated UTF-8 (ASCII in
 * practice).
 *
 * Writes 77 bytes (each 0 or 1) to `out_message77`. Returns
 * `MfskStatus::Ok` on success, `InvalidArg` if any string fails to
 * pack (callsign too long, bad characters, etc) — see
 * [`mfsk_ft8_last_error`] for the specific reason.
 *
 * # Safety
 * `call1`, `call2`, `report` must point to valid NUL-terminated
 * C strings. `out_message77` must point to a writable 77-byte
 * buffer.
 */

enum MfskStatus mfsk_ft8_pack77(const char *call1,
                                const char *call2,
                                const char *report,
                                uint8_t *out_message77);

/**
 * Convert a 77-bit FT8 message into the 79-tone Gray-mapped
 * sequence. Wraps `mfsk_core::ft8::wave_gen::message_to_tones`.
 * LDPC encode + CRC-14 + Costas insertion all happen inside.
 *
 * `message77` must point to 77 valid bytes (each 0 or 1).
 * `out_itone` receives 79 bytes (each 0..7).
 *
 * # Safety
 * Both pointers must be non-null and writable for their lengths.
 */
 enum MfskStatus mfsk_ft8_message_to_tones(const uint8_t *message77, uint8_t *out_itone);

/**
 * Synthesise FT8 i16 PCM (12 kHz mono) from a 79-tone sequence
 * into a caller-provided buffer. `out` must be at least
 * [`mfsk_ft8_synth_output_len`] = 151 680 samples; longer is fine
 * (only the prefix is written). `f0_hz` is the carrier frequency
 * (typical 1500 Hz). `amplitude_i16` peaks at the given value
 * (typical 16 384 ≈ i16_max / 2 for ~50 % full scale headroom).
 *
 * Output covers 12.64 s of audio (79 symbols × 1920 samples /
 * 12 kHz). Caller is responsible for slot-aligning this within an
 * FT8 14-second window if transmitting (typical: prepend 0.5 s of
 * silence + append 0.86 s of trailing silence to match the
 * receive-side `TX_START_OFFSET_S`).
 *
 * # Safety
 * `itone` must point to 79 valid bytes (each 0..7). `out` must
 * point to a writable buffer of at least `out_len` i16 samples.
 * Returns `InvalidArg` if `out_len < TONES_OUTPUT_LEN` (see
 * [`mfsk_ft8_last_error`]).
 */

enum MfskStatus mfsk_ft8_tones_to_i16(const uint8_t *itone,
                                      float f0_hz,
                                      int16_t amplitude_i16,
                                      int16_t *out,
                                      uintptr_t out_len);

/**
 * f32 variant of [`mfsk_ft8_tones_to_i16`]. `amplitude` is unitless
 * (typical 0.5 for ~−6 dBFS). Same buffer-length rules.
 *
 * # Safety
 * Same as [`mfsk_ft8_tones_to_i16`] — `itone` must point to 79
 * valid bytes, `out` must point to a writable f32 buffer of at
 * least `out_len` samples; returns `InvalidArg` if `out_len` is
 * below `mfsk_ft8_synth_output_len()` (see [`mfsk_ft8_last_error`]).
 */

enum MfskStatus mfsk_ft8_tones_to_f32(const uint8_t *itone,
                                      float f0_hz,
                                      float amplitude,
                                      float *out,
                                      uintptr_t out_len);

/**
 * Allocate a new streaming wrapper.
 *
 * `src_rate_hz`: the rate at which the caller will push samples
 * (typically 16000 / 24000 / 48000). Resampled internally to 12 kHz.
 * Must be > 0; pass `12000` to bypass the resampler.
 *
 * `capacity_samples`: 12 kHz ring-buffer capacity. Pass `180_000`
 * for the standard 15 s FT8 slot. Smaller values save memory at the
 * cost of less history; larger values let the decoder lag without
 * overwriting. Must be ≥ 168_000 (the `decode_block` minimum) for
 * the typical "snapshot the latest 15 s and decode" pattern.
 *
 * Returns `NULL` on `src_rate_hz == 0`, `capacity_samples == 0`, or
 * allocation failure.
 *
 * # Safety
 * Free with [`mfsk_ft8_stream_free`].
 */
 struct MfskFt8Stream *mfsk_ft8_stream_new(uint32_t src_rate_hz, uintptr_t capacity_samples);

/**
 * Free a stream allocated by [`mfsk_ft8_stream_new`]. Pointer must
 * not be used afterwards. `NULL` is safe (no-op).
 *
 * # Safety
 * `stream` must be a pointer previously returned by
 * [`mfsk_ft8_stream_new`] and not yet freed.
 */
 void mfsk_ft8_stream_free(struct MfskFt8Stream *stream);

/**
 * Push `n` source-rate i16 samples into the stream. Resamples to
 * 12 kHz internally and appends to the ring (oldest samples
 * overwritten if the ring is full).
 *
 * Returns [`MfskStatus::Ok`] on success, [`MfskStatus::NullPointer`]
 * if `stream` or `samples` is null (or `n == 0` with non-null
 * samples is allowed and is a no-op).
 *
 * # Safety
 * `samples` must point to `n` valid `i16` values; `stream` must be a
 * live handle from [`mfsk_ft8_stream_new`].
 */

enum MfskStatus mfsk_ft8_stream_push_i16(struct MfskFt8Stream *stream,
                                         const int16_t *samples,
                                         uintptr_t n);

/**
 * Number of 12 kHz samples currently buffered.
 *
 * # Safety
 * `stream` must be a live handle from [`mfsk_ft8_stream_new`].
 * Returns 0 if `stream` is null.
 */
 uintptr_t mfsk_ft8_stream_buffered_samples(const struct MfskFt8Stream *stream);

/**
 * Copy the most recent `cap` 12 kHz samples (in chronological order)
 * into `out`. Returns the number actually written —
 * `min(cap, buffered_samples)`. Does not modify the ring.
 *
 * Pass `cap = 180000` and `out`-buffer of the same size to grab a
 * standard 15 s FT8 slot for `mfsk_ft8_decode_i16`.
 *
 * # Safety
 * `stream` must be a live handle; `out` must point to `cap` writable
 * `i16`s. Returns 0 if either is null.
 */

uintptr_t mfsk_ft8_stream_peek_latest(const struct MfskFt8Stream *stream,
                                      int16_t *out,
                                      uintptr_t cap);

/**
 * Drop the oldest `n` 12 kHz samples (advance the ring tail).
 * Use after a successful decode to free room for the next slot's
 * fresh audio. Clamped to `buffered_samples`.
 *
 * # Safety
 * `stream` must be a live handle. `NULL` is a no-op.
 */
 void mfsk_ft8_stream_drain(struct MfskFt8Stream *stream, uintptr_t n);

/**
 * Discard everything in the ring buffer and reset the resampler
 * state. Use on tuning changes / band switches.
 *
 * # Safety
 * `stream` must be a live handle. `NULL` is a no-op.
 */
 void mfsk_ft8_stream_clear(struct MfskFt8Stream *stream);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MFSK_FT8_H */
