#!/usr/bin/env python3
"""Generates mfsk-core's LDPC(240,K) `tables.rs` from WSJT-X's Fortran tables.

    scripts/fst4w/gen_ldpc_tables.py <wsjtx-repo> <tag> <74|101> > tables.rs

Reads `lib/fst4/ldpc_240_<K>_{parity,generator}.f90` with `git show <tag>:...`
(never the working tree). Fortran indices are 1-based; MN and NM are written
0-based, the NM sentinel 0 (a slot past NRW, never read) stays 0 — the
convention `ldpc240_101/tables.rs` already used. The generator strings are
hex, MSB first, `K` bits of the last digit's row used (`encode240_<K>.f90`).

Run with K=101 and `cmp` the numbers against the committed 240_101 tables to
check this script before trusting its K=74 output (done for #649).
"""
import re, subprocess, sys

repo, tag, K = sys.argv[1], sys.argv[2], int(sys.argv[3])
N = 240
M = N - K

def show(name):
    return subprocess.check_output(
        ["git", "-C", repo, "show", f"{tag}:lib/fst4/{name}"], text=True)

def block(src, name):
    m = re.search(r"data\s+" + name + r"\s*/(.*?)/", src, re.S | re.I)
    body = re.sub(r"&", " ", m.group(1))
    return [int(x) for x in re.findall(r"-?\d+", body)]

par = show(f"ldpc_240_{K}_parity.f90")
mn = block(par, "Mn")
nm = block(par, "Nm")
nrw = block(par, "nrw")
assert len(mn) == 3 * N and len(nrw) == M
maxrow = len(nm) // M
assert len(nm) == maxrow * M and max(nrw) == maxrow
assert re.search(r"ncw\s*=\s*3", par)

gsrc = show(f"ldpc_240_{K}_generator.f90")
rows = re.findall(r'"([0-9a-fA-F]+)"', gsrc)
assert len(rows) == M, len(rows)

def bits(h):
    s = "".join(f"{int(c, 16):04b}" for c in h)
    return [int(c) for c in s[:K]]

out = []
w = out.append
w(f"//! Auto-generated by `scripts/fst4w/gen_ldpc_tables.py` from WSJT-X")
w(f"//! `lib/fst4/ldpc_240_{K}_{{parity,generator}}.f90` at `{tag}`.")
w("//! Fortran 1-based indices are converted to 0-based. Sentinel 0 (no")
w("//! variable-node attached) in NM stays 0 because it is read only up to")
w("//! the length given by NRW.")
w("")
w(f"pub const MN: [[u8; 3]; {N}] = [")
for i in range(N):
    a = mn[3 * i:3 * i + 3]
    w("    [" + ", ".join(str(x - 1) for x in a) + "],")
w("];")
w("")
w(f"pub const NM: [[u8; {maxrow}]; {M}] = [")
for j in range(M):
    a = nm[maxrow * j:maxrow * j + maxrow]
    w("    [" + ", ".join(str(x - 1 if x else 0) for x in a) + "],")
w("];")
w("")
w(f"pub const NRW: [u8; {M}] = [")
for i in range(0, M, 32):
    w("    " + ", ".join(str(x) for x in nrw[i:i + 32]) + ",")
w("];")
w("")
w(f"// Generator sub-matrix from `lib/fst4/ldpc_240_{K}_generator.f90`")
w(f"// — {M} rows of hex strings, first {K} bits of each row used.")
w("")
w(f"pub const GEN_PARITY: [[u8; {K}]; {M}] = [")
for r in rows:
    w("    [" + ", ".join(str(b) for b in bits(r)) + "],")
w("];")
print("\n".join(out))
