#!/usr/bin/env bash
# Golden rows for FST4W receive: WSJT-X's own `jt9 -W` (v3.3.0-beta1) over the
# cases of mfsk-core/tests/fst4w_decode.rs.
#
#   scripts/fst4w/gen_decode_vectors.sh [jt9] [out-file]
#
#   jt9       target/upstream/build-v3.3.0-beta1/jt9 (scripts/build_jt9_upstream.sh)
#   out-file  embedded-poc/assets/golden/fst4w/decode_beta1.tsv
#
# The test's `write_vectors` renders each case (this crate's transmitter plus
# seeded Gaussian noise) to a WAV; jt9 decodes it as the FST4W GUI would
# (`-W -p <period> -d 3 -f 1500 -F 100`); its rows are the TSV. Nothing large is
# vendored: the samples are regenerated by the test, and only these rows are kept.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
JT9="${1:-$REPO_ROOT/target/upstream/build-v3.3.0-beta1/jt9}"
OUT="${2:-$REPO_ROOT/embedded-poc/assets/golden/fst4w/decode_beta1.tsv}"
[ -x "$JT9" ] || { echo "no $JT9 - see scripts/build_jt9_upstream.sh" >&2; exit 1; }
W="$(mktemp -d)"; trap 'rm -rf "$W"' EXIT
FST4W_VECTOR_DIR="$W" cargo test -p mfsk-core --release --features full,internal-testing \
  --test fst4w_decode write_vectors -- --ignored >/dev/null
COMMIT="$(git -C "$REPO_ROOT/../WSJT-X" rev-parse v3.3.0-beta1^{commit} 2>/dev/null || echo unknown)"
{
  echo "# WSJT-X v3.3.0-beta1 ($COMMIT) jt9 -W -d 3 -f 1500 -F 100 over mfsk-core/tests/fst4w_decode.rs's cases"
  echo "# case	message	freq Hz	dt s	snr dB"
  for f in "$W"/*.wav; do
    name="$(basename "$f" .wav)"
    period="${name#w}"; period="${period%%_*}"
    cp "$f" "$W/000000_0000.wav"
    (cd "$W" && "$JT9" -W -p "$period" -d 3 -f 1500 -F 100 000000_0000.wav) 2>/dev/null |
      python3 -I -c '
import re, sys
name = sys.argv[1]
for line in sys.stdin:
    m = re.match(r"^\s*\d+\s+(-?\d+)\s+(-?[\d.]+)\s+(\d+)\s+\S+\s+(.*?)\s*$", line)
    if m:
        snr, dt, freq, msg = m.groups()
        print("\t".join([name, msg, freq, dt, snr]))
' "$name"
  done
} > "$OUT"
echo "$(grep -vc '^#' "$OUT") rows -> $OUT"
